version: '3.8'

services:
  baseplate-v2-frontend:
    image: baseplate-v2-frontend:latest
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${NOTIFICATION_EMAIL}
      VIRTUAL_PORT: ${VIRTUAL_PORT}      
    env_file:
      - ./.env.frontend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "15m"
        max-file: "3"

